### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by zenandreas** [j0ach1mmall3/FreeAutoMessage#4]
Plugin version: Latest ( the error appeared after adding last versions )
Server version: Paperspigot 1.8
Every single config file ( i only edited chat.yml )
Plugins list : http://prntscr.com/ao2w2m

```
[08:42:51] [Server thread/WARN]: [FreeAutoMessage] Task #554 for FreeAutoMessage v1.3.1 generated an exception
java.lang.NullPointerException
    at com.j0ach1mmall3.freeautomessage.api.PlayerBroadcaster.broadcast(PlayerBroadcaster.java:34) ~[?:?]
    at com.j0ach1mmall3.freeautomessage.api.Broadcaster.broadcast(Broadcaster.java:56) ~[?:?]
    at com.j0ach1mmall3.freeautomessage.BroadcastScheduler.run(BroadcastScheduler.java:19) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[PaperSpigot.jar:git-PaperSpigot-"8b18730"]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
[08:43:21] [Server thread/WARN]: [FreeAutoMessage] Task #554 for FreeAutoMessage v1.3.1 generated an exception
java.lang.NullPointerException
    at com.j0ach1mmall3.freeautomessage.api.PlayerBroadcaster.broadcast(PlayerBroadcaster.java:34) ~[?:?]
    at com.j0ach1mmall3.freeautomessage.api.Broadcaster.broadcast(Broadcaster.java:56) ~[?:?]
    at com.j0ach1mmall3.freeautomessage.BroadcastScheduler.run(BroadcastScheduler.java:19) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[PaperSpigot.jar:git-PaperSpigot-"8b18730"]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
```

**Comment by j0ach1mmall3** [comment]
Fixed in the latest update
