### ISSUE TITLE
Json not visible in chat.

### ISSUE THREAD

**Issue by TheW1** [j0ach1mmall3/FreeAutoMessage#5]
The Json part of chat broadcasted messages does not show up. The plain text is visible in chat, but the Json part is not.

Running craftbukkit.
Minecraft version: 1.7.10
Using the latest version of both Free Auto Message and JLib.

chat.yml:
_______________________________________________________________________________
 # Should Chat broadcasting be enabled?
Enabled: true
 # Should Json Chat formatting be enabled? (Note: requires Minecraft version 1.7!)
Json: true
ChatBroadcasters:
  ExampleChatBroadcaster:
    # Should the order be randomized?
    Random: false
    # The worlds in which this Broadcaster will be active
    EnabledWorlds:
    - world
    # The interval between each messages in ticks (1 second = 20 ticks)
    Interval: 600
    # The permission a player needs to have to see the messages
    Permission: example.chat.broadcaster
    # The messages of this Broadcaster (Placeholders and Color codes (& symbol) work here)
    # You can use Json formatting in the messages
    # Use [text] in front of normal text to ignore json
    # You can use the | symbol between text or between json declarations to create a new line
    Messages:
    - '[text]&7-------------------|[text]&6This server uses &dFreeAutoMessage&6, a free Auto Messaging plugin that has some very cool features!|{"text":"Check it out here!","color":"gray","clickEvent":{"action":"open_url","value":"https://www.spigotmc.org/resources/11191/"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Click to check it out!","color":"dark_purple"}]}}}|[text]&7-------------------'
    - '[text]&dFreeAutoMessage &6supports a lot of broadcasting methods, including &lActionbar, Boss Bar, Chat, Command, Signs, Subtitle, Title and Tablist Broadcasters&6!|[text]&6And all of that, at the cheap price of &l0$&6!'
DoNotChange: 1.1.0
_______________________________________________________________________________

When joining the server and the first message is broadcasted(with Json part not showing up) this is shown in cmd:
_______________________________________________________________________________
[20:32:32 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_7_R4.PacketPlayOutChat.<init>(net.minecraft.server.v1_7_R4.IChatBaseComponent, byte)

[20:32:32 WARN]:        at java.lang.Class.getConstructor0(Unknown Source)

[20:32:32 WARN]:        at java.lang.Class.getConstructor(Unknown Source)

[20:32:32 WARN]:        at com.j0ach1mmall3.jlib.visual.JsonText.send(JsonText.java:74)

[20:32:32 WARN]:        at com.j0ach1mmall3.freeautomessage.api.ChatBroadcaster.broadcastInternal(ChatBroadcaster.java:24)

[20:32:32 WARN]:        at com.j0ach1mmall3.freeautomessage.api.WorldsBroadcaster.broadcast(WorldsBroadcaster.java:28)

[20:32:32 WARN]:        at com.j0ach1mmall3.freeautomessage.api.Broadcaster.broadcast(Broadcaster.java:56)

[20:32:32 WARN]:        at com.j0ach1mmall3.freeautomessage.BroadcastScheduler.run(BroadcastScheduler.java:19)

[20:32:32 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:53)

[20:32:32 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349)

[20:32:32 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:600)

[20:32:32 WARN]:        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:258)

[20:32:32 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:558)

[20:32:32 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:469)

[20:32:32 WARN]:        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
_______________________________________________________________________________

**Comment by j0ach1mmall3** [comment]
Should be fixed in the latest JLib build

**Comment by TheW1** [comment]
Yep, just tried it and I can confirm that it works! Great work!

Thanks!
Den 13 apr 2016 4:26 em skrev "j0ach1mmall3" <notifications@github.com>:
