### ISSUE TITLE
JLib? 1.8.8 compat? Won't run.

### ISSUE THREAD

**Issue by AeSix** [j0ach1mmall3/FreeAutoMessage#9]
I'm getting an error attempting to load this on my 1.8.8 server.  I see on the plugin's plage it's supposed to support 1.7, 1.8, 1.9  - and yet it appears to no do so?  Or did I miss that there's another file somewhere I'm supposed to grab?

Server:
[16:54:14 INFO]: This server is running CraftBukkit version git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Error:
[16:54:14 ERROR]: Could not load 'plugins/FreeAutoMessage.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: JLib
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot-  catfight.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot-catfight.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot-catfight.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-catfight.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

**Comment by AeSix** [comment]
nevermind.
https://www.spigotmc.org/resources/jlib.6603/
I just didn't see it linked before.
